# Generated by Django 2.2.12 on 2023-05-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('role', models.CharField(choices=[('A', 'Admin'), ('N', 'Normal'), ('T', 'Trador')], max_length=1)),
                ('email', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=225)),
            ],
        ),
    ]
