# Generated by Django 2.2.12 on 2023-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230505_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('N', 'Normal'), ('T', 'Trador')], default=('N', 'Normal'), max_length=255),
        ),
    ]
